---
- name: deploying spring petclinic as linux service
  hosts: appserver
  become: yes
  vars:
    java_package: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic
    app_file_name: spring-petclinic-2.4.2.jar
    app_download_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_username: springbootuser
    test_var: just for testting
  tasks:
    - name: display the java package
      debug: 
        var: java_package
    - name: checking the variables
      debug:
        var: test_var
    - name: updating the packages and installing java 
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: creating a springpetclinic directory
      file:
        path: "{{ app_dir }}"
        state: directory
    - name: downloading springpetclinic
      get_url: 
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/{{app_file_name}}
        dest: "{{ app_dir }}/{{ app_file_name }}"
    - name: creating a springboot user 
      user:
        name: "{{ app_username }}"
        password: "{{ app_username }}"
        state: present 
    - name: changing the ownership of the file
      file:
        path: "{{ app_dir }}/{{ app_file_name }}"
        owner: "{{ app_username }}"
        mode: 500
        state: file 
    - name: copying the service file 
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: enabling and starting the springpetclinic serivice file 
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started
         
        