---
- name: deploying spring petclinic as linux service
  hosts: appserver
  become: yes
  tasks:
    - name: updating the packages and installing java 
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: creating a springpetclinic directory
      file:
        path: /usr/share/springpetclinic
        state: directory
    - name: downloading springpetclinic
      get_url: 
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    - name: creating a springboot user 
      user:
        name: springbootuser
        password: springbootuser
        state: present 
    - name: changing the ownership of the file
      file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: 500
        state: file 
    - name: copying the service file 
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: enabling and starting the springpetclinic serivice file 
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started
         
        